from app.models.base import SessionLocal
from app.models.cerveza import Cerveza
from app.models.ingrediente import Ingrediente, CervezaIngrediente
from app.models.paso import Paso
from app.models.usuario import Usuario
from app.models.notificacion import Notificacion
from app.models.comentario import Comentario

RECETAS = [
    {
        "nombre": "Cascade IPA",
        "descripcion": "Una IPA americana clásica con notas cítricas y resinosas de lúpulo Cascade. Amarga y refrescante, perfecta para los amantes del lúpulo.",
        "estilo": "IPA",
        "litros": 20,
        "alcohol": 6.2,
        "amargor": 55,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 4500, "g"),
            ("Malta Caramelo", 300, "g"),
            ("Lúpulo Cascade", 80, "g"),
            ("Lúpulo Centennial", 40, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar los granos a 66°C durante 60 minutos", 60),
            ("Hervir el mosto durante 60 minutos añadiendo lúpulo Cascade al inicio", 60),
            ("Añadir lúpulo Centennial en los últimos 10 minutos", 10),
            ("Enfriar a 20°C y transferir al fermentador", 30),
            ("Inocular la levadura y fermentar a 19°C durante 14 días", None),
            ("Embotellar con azúcar de refermentación", None),
        ],
    },
    {
        "nombre": "Stout Café y Vainilla",
        "descripcion": "Una Stout oscura y cremosa con notas de café tostado y un toque de vainilla. Cuerpo denso y final largo.",
        "estilo": "Stout",
        "litros": 20,
        "alcohol": 5.8,
        "amargor": 35,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 3500, "g"),
            ("Malta Chocolate", 500, "g"),
            ("Malta Negra", 300, "g"),
            ("Malta Avena", 400, "g"),
            ("Lúpulo Fuggle", 40, "g"),
            ("Levadura Ale Inglesa", 1, "ud"),
            ("Café", 50, "g"),
            ("Vainilla", 2, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 68°C durante 75 minutos para mayor cuerpo", 75),
            ("Hervir 60 minutos con lúpulo Fuggle al inicio", 60),
            ("Añadir café molido en los últimos 5 minutos del hervor", 5),
            ("Enfriar a 18°C y fermentar con levadura inglesa", None),
            ("Añadir vainilla en seco durante la fermentación secundaria", None),
            ("Embotellar tras 21 días de fermentación", None),
        ],
    },
    {
        "nombre": "Hefeweizen Bávara",
        "descripcion": "Cerveza de trigo bávara tradicional con aromas a plátano y clavo de la levadura Weizen. Turbia, refrescante y ligera.",
        "estilo": "Hefeweizen",
        "litros": 20,
        "alcohol": 5.0,
        "amargor": 12,
        "dias_fermentacion": 7,
        "intervalo_horas": 8,
        "ingredientes": [
            ("Malta Trigo", 2800, "g"),
            ("Malta Pilsner", 1800, "g"),
            ("Lúpulo Hallertau", 25, "g"),
            ("Levadura Weizen", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Realizar maceración escalonada: 45°C 15min, 62°C 30min, 72°C 30min", 75),
            ("Hervir 60 minutos con Hallertau al inicio", 60),
            ("Enfriar a 16°C y fermentar con levadura Weizen", None),
            ("Fermentar a 18°C durante 7 días sin filtrar", None),
            ("Embotellar con refermentación en botella", None),
        ],
    },
    {
        "nombre": "Saison Provenzal",
        "descripcion": "Saison belga con notas especiadas y frutales. Seca, efervescente y con un final largo característico de la levadura Saison.",
        "estilo": "Saison",
        "litros": 20,
        "alcohol": 6.5,
        "amargor": 28,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 3800, "g"),
            ("Malta Trigo", 600, "g"),
            ("Lúpulo Saaz", 35, "g"),
            ("Lúpulo Hallertau", 20, "g"),
            ("Levadura Saison", 1, "ud"),
            ("Naranja", 2, "ud"),
            ("Cilantro", 15, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 64°C durante 60 minutos para perfil seco", 60),
            ("Hervir 75 minutos, añadir Saaz al inicio y Hallertau a los 30min", 75),
            ("Añadir piel de naranja y cilantro en los últimos 5 minutos", 5),
            ("Fermentar a 24°C con levadura Saison durante 14 días", None),
            ("Embotellar y dejar refermentar 2 semanas en botella", None),
        ],
    },
    {
        "nombre": "American Pale Ale",
        "descripcion": "APA equilibrada con lúpulos americanos. Notas cítricas y florales de Cascade con un amargor moderado y malta de fondo.",
        "estilo": "APA",
        "litros": 20,
        "alcohol": 5.2,
        "amargor": 38,
        "dias_fermentacion": 10,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 4000, "g"),
            ("Malta Caramelo", 250, "g"),
            ("Lúpulo Cascade", 50, "g"),
            ("Lúpulo Amarillo", 30, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 60 minutos", 60),
            ("Hervir 60 minutos, Cascade al inicio", 60),
            ("Añadir Amarillo a los 10 minutos del final", 10),
            ("Dry hop con Cascade durante 3 días", None),
            ("Embotellar tras 10 días de fermentación", None),
        ],
    },
    {
        "nombre": "Porter Inglesa",
        "descripcion": "Porter tradicional inglesa con notas de chocolate oscuro, café y caramelo. Robusta pero bebible.",
        "estilo": "Porter",
        "litros": 20,
        "alcohol": 5.4,
        "amargor": 30,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 3200, "g"),
            ("Malta Chocolate", 400, "g"),
            ("Malta Crystal", 350, "g"),
            ("Malta Munich", 300, "g"),
            ("Lúpulo Fuggle", 45, "g"),
            ("Levadura Ale Inglesa", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Fuggle al inicio y a los 30min", 60),
            ("Enfriar a 18°C y fermentar con levadura inglesa", None),
            ("Fermentar 14 días a temperatura estable", None),
            ("Embotellar con azúcar de refermentación", None),
        ],
    },
    {
        "nombre": "NEIPA Tropical",
        "descripcion": "New England IPA con lúpulos tropicales. Turbidez característica, suave amargor y explosión de frutas tropicales en aroma y sabor.",
        "estilo": "NEIPA",
        "litros": 20,
        "alcohol": 6.8,
        "amargor": 40,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 4000, "g"),
            ("Malta Avena", 600, "g"),
            ("Malta Trigo", 400, "g"),
            ("Lúpulo Citra", 80, "g"),
            ("Lúpulo Mosaic", 60, "g"),
            ("Lúpulo Galaxy", 40, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Lactosa", 200, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 60 minutos", 60),
            ("Hervir 60 minutos, añadir Citra al inicio", 60),
            ("Whirlpool con Mosaic y Galaxy durante 20 minutos", 20),
            ("Fermentar a 19°C durante 7 días", None),
            ("Dry hop con Citra y Mosaic durante 4 días", None),
            ("Embotellar tras 14 días totales", None),
        ],
    },
    {
        "nombre": "Lager Clásica",
        "descripcion": "Lager limpia y refrescante al estilo centroeuropeo. Notas de malta suave, lúpulo floral y final seco. Perfecta para el verano.",
        "estilo": "Lager",
        "litros": 20,
        "alcohol": 4.8,
        "amargor": 18,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 4200, "g"),
            ("Malta Viena", 300, "g"),
            ("Lúpulo Saaz", 40, "g"),
            ("Lúpulo Hallertau", 20, "g"),
            ("Levadura Lager", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Maceración escalonada: 52°C 20min, 62°C 30min, 72°C 20min", 70),
            ("Hervir 90 minutos, Saaz al inicio y Hallertau a los 60min", 90),
            ("Enfriar a 10°C y fermentar con levadura Lager", None),
            ("Fermentación primaria a 10°C durante 14 días", None),
            ("Lagering a 2°C durante 7 días adicionales", None),
            ("Embotellar con refermentación controlada", None),
        ],
    },
    {
        "nombre": "Belgian Dubbel",
        "descripcion": "Dubbel belga con notas de frutas oscuras, caramelo y especias. Cuerpo medio y dulzor equilibrado con la levadura belga.",
        "estilo": "Dubbel",
        "litros": 20,
        "alcohol": 7.0,
        "amargor": 22,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 3500, "g"),
            ("Malta Munich", 800, "g"),
            ("Malta Caramelo", 400, "g"),
            ("Malta Chocolate", 150, "g"),
            ("Lúpulo Hallertau", 35, "g"),
            ("Levadura Belga", 1, "ud"),
            ("Azúcar de caña", 300, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 75 minutos", 75),
            ("Hervir 90 minutos con Hallertau al inicio", 90),
            ("Añadir azúcar de caña a los 15 minutos del final", 15),
            ("Fermentar a 20°C con levadura belga", None),
            ("Dejar subir temperatura a 24°C en los últimos días", None),
            ("Embotellar y refermentar en botella 3 semanas", None),
        ],
    },
    {
        "nombre": "Gose con Mango",
        "descripcion": "Gose alemana refrescante con mango tropical. Ligeramente ácida, salada y afrutada. Ideal para días calurosos.",
        "estilo": "Gose",
        "litros": 20,
        "alcohol": 4.2,
        "amargor": 8,
        "dias_fermentacion": 7,
        "intervalo_horas": 8,
        "ingredientes": [
            ("Malta Trigo", 2500, "g"),
            ("Malta Pilsner", 1500, "g"),
            ("Lúpulo Hallertau", 15, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Mango", 500, "g"),
            ("Cilantro", 10, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 64°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Hallertau al inicio", 60),
            ("Añadir cilantro en los últimos 5 minutos", 5),
            ("Fermentar a 20°C durante 7 días", None),
            ("Añadir puré de mango en fermentación secundaria", None),
            ("Embotellar tras fermentación completa", None),
        ],
    },
    {
        "nombre": "Imperial Stout Cacao",
        "descripcion": "Imperial Stout con cacao y un toque de miel. Potente, oscura y compleja. Para degustar despacio en los meses fríos.",
        "estilo": "Imperial Stout",
        "litros": 20,
        "alcohol": 9.5,
        "amargor": 60,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 5000, "g"),
            ("Malta Chocolate", 700, "g"),
            ("Malta Negra", 400, "g"),
            ("Malta Avena", 500, "g"),
            ("Lúpulo Chinook", 60, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Cacao", 100, "g"),
            ("Miel", 200, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 68°C durante 75 minutos", 75),
            ("Hervir 90 minutos con Chinook al inicio y a los 45min", 90),
            ("Añadir miel en los últimos 10 minutos", 10),
            ("Fermentar a 20°C durante 21 días", None),
            ("Añadir cacao en seco durante la semana 2", None),
            ("Embotellar y madurar mínimo 1 mes", None),
        ],
    },
    {
        "nombre": "Red Ale Irlandesa",
        "descripcion": "Red Ale de inspiración irlandesa con malta tostada y caramelo. Equilibrada, de color rojizo intenso y fácil de beber.",
        "estilo": "Red Ale",
        "litros": 20,
        "alcohol": 4.5,
        "amargor": 25,
        "dias_fermentacion": 10,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 3500, "g"),
            ("Malta Crystal", 400, "g"),
            ("Malta Caramelo", 300, "g"),
            ("Malta Chocolate", 100, "g"),
            ("Lúpulo Fuggle", 35, "g"),
            ("Levadura Ale Inglesa", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Fuggle al inicio y a los 30min", 60),
            ("Enfriar a 18°C y fermentar con levadura inglesa", None),
            ("Fermentar 10 días a temperatura estable", None),
            ("Embotellar con refermentación", None),
        ],
    },
    {
        "nombre": "Wheat Beer Americana",
        "descripcion": "American Wheat Beer ligera y refrescante con un toque de naranja y cilantro. Más filtrada que la Hefeweizen y con lúpulos americanos.",
        "estilo": "Wheat Beer",
        "litros": 20,
        "alcohol": 4.8,
        "amargor": 15,
        "dias_fermentacion": 7,
        "intervalo_horas": 8,
        "ingredientes": [
            ("Malta Trigo", 2500, "g"),
            ("Malta Pale Ale", 2000, "g"),
            ("Lúpulo Cascade", 25, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Naranja", 1, "ud"),
            ("Cilantro", 8, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 65°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Cascade al inicio", 60),
            ("Añadir naranja y cilantro en los últimos 5 minutos", 5),
            ("Fermentar a 20°C durante 7 días", None),
            ("Embotellar sin filtrar para mayor turbidez", None),
        ],
    },
    {
        "nombre": "Kölsch Clásica",
        "descripcion": "Kölsch de Colonia, ligera y dorada con un equilibrio perfecto entre malta y lúpulo. Fermentada con levadura ale y lagered en frío.",
        "estilo": "Kölsch",
        "litros": 20,
        "alcohol": 4.8,
        "amargor": 20,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 3800, "g"),
            ("Malta Trigo", 400, "g"),
            ("Lúpulo Hallertau", 30, "g"),
            ("Lúpulo Saaz", 15, "g"),
            ("Levadura Ale Alemana", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 65°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Hallertau al inicio", 60),
            ("Añadir Saaz en los últimos 15 minutos", 15),
            ("Fermentar a 16°C durante 10 días", None),
            ("Lager a 4°C durante 4 días adicionales", None),
            ("Embotellar filtrada", None),
        ],
    },
    {
        "nombre": "Sour Frambuesa",
        "descripcion": "Cerveza ácida con frambuesa. Refrescante, afrutada y con la acidez característica de las sours. Color rosado intenso.",
        "estilo": "Sour",
        "litros": 20,
        "alcohol": 4.5,
        "amargor": 5,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 3000, "g"),
            ("Malta Trigo", 1000, "g"),
            ("Lúpulo Saaz", 10, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Frambuesa", 800, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 64°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Saaz al inicio", 60),
            ("Acidificar el mosto antes de fermentar", None),
            ("Fermentar a 20°C durante 14 días", None),
            ("Añadir puré de frambuesa y fermentar 7 días más", None),
            ("Embotellar y madurar 2 semanas", None),
        ],
    },
    {
        "nombre": "Amber Ale con Miel",
        "descripcion": "Amber Ale americana con miel natural. Notas de caramelo y floral de la miel con un amargor moderado de lúpulos americanos.",
        "estilo": "Amber Ale",
        "litros": 20,
        "alcohol": 5.5,
        "amargor": 30,
        "dias_fermentacion": 10,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 3500, "g"),
            ("Malta Caramelo", 400, "g"),
            ("Malta Viena", 300, "g"),
            ("Lúpulo Cascade", 40, "g"),
            ("Lúpulo Centennial", 20, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Miel", 300, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Cascade al inicio", 60),
            ("Añadir miel y Centennial en los últimos 10 minutos", 10),
            ("Fermentar a 19°C durante 10 días", None),
            ("Embotellar con refermentación", None),
        ],
    },
    {
        "nombre": "Brown Ale Inglesa",
        "descripcion": "Brown Ale inglesa con notas de nuez, chocolate suave y caramelo. Suave amargor y final seco característico de la levadura inglesa.",
        "estilo": "Brown Ale",
        "litros": 20,
        "alcohol": 4.8,
        "amargor": 25,
        "dias_fermentacion": 10,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 3200, "g"),
            ("Malta Crystal", 400, "g"),
            ("Malta Chocolate", 200, "g"),
            ("Malta Munich", 300, "g"),
            ("Lúpulo Fuggle", 30, "g"),
            ("Lúpulo Hallertau", 15, "g"),
            ("Levadura Ale Inglesa", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 67°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Fuggle al inicio y Hallertau a los 30min", 60),
            ("Fermentar a 18°C durante 10 días", None),
            ("Embotellar con azúcar de refermentación", None),
        ],
    },
    {
        "nombre": "Pilsner Bohemia",
        "descripcion": "Pilsner checa con el inconfundible lúpulo Saaz. Dorada, brillante y con un amargor herbáceo y floral muy característico.",
        "estilo": "Pilsner",
        "litros": 20,
        "alcohol": 4.5,
        "amargor": 35,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 4000, "g"),
            ("Lúpulo Saaz", 60, "g"),
            ("Levadura Lager", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Maceración escalonada: 52°C 20min, 63°C 30min, 72°C 20min", 70),
            ("Hervir 90 minutos con Saaz en tres adiciones", 90),
            ("Enfriar a 8°C y fermentar con levadura Lager", None),
            ("Fermentación a 10°C durante 14 días", None),
            ("Lagering a 2°C durante 7 días", None),
            ("Embotellar filtrada y brillante", None),
        ],
    },
    {
        "nombre": "Tripel Belga",
        "descripcion": "Tripel belga de alta graduación, dorada y efervescente. Frutal, especiada y seca con el carácter único de la levadura belga.",
        "estilo": "Tripel",
        "litros": 20,
        "alcohol": 8.5,
        "amargor": 30,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pilsner", 5000, "g"),
            ("Lúpulo Saaz", 40, "g"),
            ("Lúpulo Hallertau", 20, "g"),
            ("Levadura Belga", 1, "ud"),
            ("Azúcar de caña", 500, "g"),
            ("Naranja", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 63°C durante 75 minutos para perfil seco", 75),
            ("Hervir 90 minutos con Saaz al inicio y Hallertau a los 60min", 90),
            ("Añadir azúcar de caña y piel de naranja en los últimos 10min", 10),
            ("Fermentar a 20°C subiendo a 26°C progresivamente", None),
            ("Fermentar 21 días totales", None),
            ("Embotellar con refermentación y madurar 1 mes", None),
        ],
    },
    {
        "nombre": "Session IPA Citra",
        "descripcion": "Session IPA baja en alcohol pero intensa en aroma. Lúpulo Citra protagonista con notas de lima, maracuyá y pomelo. Muy refrescante.",
        "estilo": "IPA",
        "litros": 20,
        "alcohol": 3.8,
        "amargor": 35,
        "dias_fermentacion": 10,
        "intervalo_horas": 8,
        "ingredientes": [
            ("Malta Pale Ale", 2800, "g"),
            ("Malta Trigo", 400, "g"),
            ("Lúpulo Citra", 70, "g"),
            ("Lúpulo Mosaic", 30, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Maracuyá", 200, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 65°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Citra al inicio", 60),
            ("Whirlpool con Mosaic durante 15 minutos", 15),
            ("Fermentar a 19°C durante 7 días", None),
            ("Dry hop con Citra 3 días antes de embotellar", None),
            ("Embotellar tras 10 días totales", None),
        ],
    },
    {
        "nombre": "Barley Wine Ahumada",
        "descripcion": "Barley Wine con malta ahumada para añadir complejidad. Alta graduación, dulce y robusta con notas de humo, caramelo y frutos secos.",
        "estilo": "Barley Wine",
        "litros": 20,
        "alcohol": 10.0,
        "amargor": 70,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 6000, "g"),
            ("Malta Ahumada", 500, "g"),
            ("Malta Caramelo", 500, "g"),
            ("Malta Crystal", 300, "g"),
            ("Lúpulo Chinook", 80, "g"),
            ("Lúpulo Simcoe", 40, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 68°C durante 90 minutos", 90),
            ("Hervir 90 minutos con Chinook al inicio y a los 45min", 90),
            ("Añadir Simcoe en los últimos 15 minutos", 15),
            ("Fermentar a 20°C durante 21 días", None),
            ("Madurar en frío 2 semanas adicionales", None),
            ("Embotellar y madurar mínimo 3 meses", None),
        ],
    },
    {
        "nombre": "Märzen Oktoberfest",
        "descripcion": "Märzen tradicional de Oktoberfest. Dorada-ambar, maltosa y limpia con notas de pan tostado y un amargor suave y equilibrado.",
        "estilo": "Märzen",
        "litros": 20,
        "alcohol": 5.8,
        "amargor": 22,
        "dias_fermentacion": 21,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Viena", 2500, "g"),
            ("Malta Munich", 1500, "g"),
            ("Malta Pilsner", 800, "g"),
            ("Lúpulo Hallertau", 35, "g"),
            ("Lúpulo Saaz", 20, "g"),
            ("Levadura Lager", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Maceración escalonada: 52°C 15min, 63°C 30min, 72°C 25min", 70),
            ("Hervir 90 minutos con Hallertau al inicio y Saaz a los 60min", 90),
            ("Fermentar a 9°C durante 14 días", None),
            ("Lagering a 2°C durante 7 días", None),
            ("Embotellar filtrada", None),
        ],
    },
    {
        "nombre": "Cerveza de Jengibre y Limón",
        "descripcion": "Cerveza artesanal con jengibre fresco y limón. Refrescante y especiada, con un toque picante del jengibre y acidez del limón.",
        "estilo": "Wheat Beer",
        "litros": 20,
        "alcohol": 4.2,
        "amargor": 10,
        "dias_fermentacion": 7,
        "intervalo_horas": 8,
        "ingredientes": [
            ("Malta Pilsner", 2500, "g"),
            ("Malta Trigo", 1500, "g"),
            ("Lúpulo Hallertau", 15, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Jengibre", 50, "g"),
            ("Limón", 3, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 65°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Hallertau al inicio", 60),
            ("Añadir jengibre rallado y piel de limón en los últimos 5 minutos", 5),
            ("Fermentar a 20°C durante 7 días", None),
            ("Embotellar y dejar madurar 1 semana", None),
        ],
    },
    {
        "nombre": "Stout de Avena",
        "descripcion": "Oatmeal Stout cremosa y suave. La avena aporta cuerpo y textura sedosa. Notas de chocolate con leche y café con leche.",
        "estilo": "Stout",
        "litros": 20,
        "alcohol": 5.2,
        "amargor": 28,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 3200, "g"),
            ("Malta Avena", 600, "g"),
            ("Malta Chocolate", 350, "g"),
            ("Malta Crystal", 250, "g"),
            ("Lúpulo Fuggle", 35, "g"),
            ("Levadura Ale Inglesa", 1, "ud"),
            ("Lactosa", 250, "g"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 68°C durante 75 minutos para cuerpo cremoso", 75),
            ("Hervir 60 minutos con Fuggle al inicio", 60),
            ("Añadir lactosa en los últimos 10 minutos", 10),
            ("Fermentar a 18°C durante 14 días", None),
            ("Embotellar con refermentación suave", None),
        ],
    },
    {
        "nombre": "IPA con Simcoe y Nelson",
        "descripcion": "IPA de doble lúpulo con Simcoe y Nelson Sauvin. Notas de fruta tropical, uva blanca y pino. Compleja y aromática.",
        "estilo": "IPA",
        "litros": 20,
        "alcohol": 6.5,
        "amargor": 60,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Pale Ale", 4200, "g"),
            ("Malta Caramelo", 200, "g"),
            ("Lúpulo Simcoe", 60, "g"),
            ("Lúpulo Nelson Sauvin", 50, "g"),
            ("Lúpulo Cascade", 30, "g"),
            ("Levadura Ale Americana", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Macerar a 66°C durante 60 minutos", 60),
            ("Hervir 60 minutos con Simcoe al inicio", 60),
            ("Añadir Nelson Sauvin a los 15 minutos del final", 15),
            ("Whirlpool con Cascade 20 minutos", 20),
            ("Fermentar a 19°C durante 10 días", None),
            ("Dry hop con Simcoe y Nelson 4 días", None),
            ("Embotellar tras 14 días totales", None),
        ],
    },
    {
        "nombre": "Dunkel Bávara",
        "descripcion": "Dunkel de Munich con malta oscura y Munich. Notas de pan tostado, chocolate suave y caramelo. Oscura pero ligera y muy bebible.",
        "estilo": "Dunkel",
        "litros": 20,
        "alcohol": 5.0,
        "amargor": 18,
        "dias_fermentacion": 14,
        "intervalo_horas": 12,
        "ingredientes": [
            ("Malta Munich", 3000, "g"),
            ("Malta Pilsner", 1000, "g"),
            ("Malta Chocolate", 200, "g"),
            ("Malta Caramelo", 200, "g"),
            ("Lúpulo Hallertau", 30, "g"),
            ("Levadura Lager", 1, "ud"),
            ("Agua", 25, "L"),
        ],
        "pasos": [
            ("Maceración escalonada: 52°C 15min, 63°C 30min, 72°C 20min", 65),
            ("Hervir 60 minutos con Hallertau al inicio y a los 30min", 60),
            ("Fermentar a 9°C durante 10 días", None),
            ("Lagering a 2°C durante 4 días", None),
            ("Embotellar filtrada", None),
        ],
    },
]


def seed_recetas(db):
    admin = db.query(Usuario).filter(Usuario.username == "admin").first()
    if not admin:
        print("❌ No se encontró el usuario admin")
        return

    existentes = db.query(Cerveza).count()
    if existentes > 0:
        print(f"⚠️  Ya existen {existentes} recetas en la BD, omitiendo seed")
        return

    for receta in RECETAS:
        cerveza = Cerveza(
            usuario_id=admin.id,
            nombre=receta["nombre"],
            descripcion=receta["descripcion"],
            estilo=receta["estilo"],
            litros=receta["litros"],
            alcohol=receta["alcohol"],
            amargor=receta["amargor"],
            dias_fermentacion=receta.get("dias_fermentacion"),
            intervalo_horas=receta.get("intervalo_horas"),
            activa=True,
        )
        db.add(cerveza)
        db.flush()

        for nombre_ing, cantidad, unidad in receta["ingredientes"]:
            ing = db.query(Ingrediente).filter(Ingrediente.nombre == nombre_ing).first()
            if ing:
                db.add(CervezaIngrediente(
                    cerveza_id=cerveza.id,
                    ingrediente_id=ing.id,
                    cantidad=cantidad,
                    unidad=unidad,
                ))

        for i, (descripcion, duracion) in enumerate(receta["pasos"]):
            db.add(Paso(
                cerveza_id=cerveza.id,
                orden=i + 1,
                descripcion=descripcion,
                duracion_min=duracion,
            ))

    db.commit()
    print(f"✅ {len(RECETAS)} recetas cargadas correctamente")


if __name__ == "__main__":
    from app.models.base import SessionLocal
    db = SessionLocal()
    try:
        seed_recetas(db)
    finally:
        db.close()