"""add reset token to usuario

Revision ID: 1eba7bd099ab
Revises: 2148b004426d
Create Date: 2026-06-28 01:33:03.178888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eba7bd099ab'
down_revision: Union[str, Sequence[str], None] = '2148b004426d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.add_column('usuarios', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expira', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'reset_token_expira')
    op.drop_column('usuarios', 'reset_token')
    op.create_table('notificaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cerveza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['usuarios.id'], name=op.f('notificaciones_actor_id_fkey')),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], name=op.f('notificaciones_cerveza_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('notificaciones_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notificaciones_pkey'))
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cerveza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], name=op.f('comentarios_cerveza_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('comentarios_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comentarios_pkey'))
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    # ### end Alembic commands ###
