"""valoraciones a me gustas

Revision ID: 5261cd05268f
Revises: 948ed06734e5
Create Date: 2026-06-11 20:47:28.594238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5261cd05268f'
down_revision: Union[str, Sequence[str], None] = '948ed06734e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('me_gustas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerveza_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cerveza_id', 'usuario_id', name='uq_megusta_usuario_cerveza')
    )
    op.create_index(op.f('ix_me_gustas_id'), 'me_gustas', ['id'], unique=False)
    op.drop_index(op.f('ix_valoraciones_id'), table_name='valoraciones')
    op.drop_table('valoraciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valoraciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cerveza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], name=op.f('valoraciones_cerveza_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('valoraciones_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('valoraciones_pkey')),
    sa.UniqueConstraint('cerveza_id', 'usuario_id', name=op.f('uq_valoracion_usuario_cerveza'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_valoraciones_id'), 'valoraciones', ['id'], unique=False)
    op.drop_index(op.f('ix_me_gustas_id'), table_name='me_gustas')
    op.drop_table('me_gustas')
    # ### end Alembic commands ###
