"""temperaturas fermentacion

Revision ID: 87453607e16a
Revises: 5261cd05268f
Create Date: 2026-06-18 01:25:08.465389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87453607e16a'
down_revision: Union[str, Sequence[str], None] = '5261cd05268f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_temperatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerveza_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_temperatura_id'), 'registros_temperatura', ['id'], unique=False)
    op.add_column('cervezas', sa.Column('dias_fermentacion', sa.Integer(), nullable=True))
    op.add_column('cervezas', sa.Column('intervalo_horas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cervezas', 'intervalo_horas')
    op.drop_column('cervezas', 'dias_fermentacion')
    op.drop_index(op.f('ix_registros_temperatura_id'), table_name='registros_temperatura')
    op.drop_table('registros_temperatura')
    # ### end Alembic commands ###
