"""add imagen_url to cerveza

Revision ID: 93565c748e2f
Revises: 2753e9e5e0ab
Create Date: 2026-06-27 17:17:10.863971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93565c748e2f'
down_revision: Union[str, Sequence[str], None] = '2753e9e5e0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.add_column('cervezas', sa.Column('imagen_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cervezas', 'imagen_url')
    op.create_table('comentarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cerveza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], name=op.f('comentarios_cerveza_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('comentarios_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comentarios_pkey'))
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cerveza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['usuarios.id'], name=op.f('notificaciones_actor_id_fkey')),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], name=op.f('notificaciones_cerveza_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('notificaciones_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notificaciones_pkey'))
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    # ### end Alembic commands ###
