"""crear tablas iniciales

Revision ID: 948ed06734e5
Revises: 
Create Date: 2026-06-10 20:47:16.962837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948ed06734e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_ingredientes_id'), 'ingredientes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('USER', 'ADMIN', name='rol'), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('cervezas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estilo', sa.String(length=50), nullable=True),
    sa.Column('litros', sa.Integer(), nullable=True),
    sa.Column('alcohol', sa.Float(), nullable=True),
    sa.Column('amargor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cervezas_id'), 'cervezas', ['id'], unique=False)
    op.create_table('cerveza_ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerveza_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerveza_ingredientes_id'), 'cerveza_ingredientes', ['id'], unique=False)
    op.create_table('pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerveza_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasos_id'), 'pasos', ['id'], unique=False)
    op.create_table('valoraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerveza_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cerveza_id'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cerveza_id', 'usuario_id', name='uq_valoracion_usuario_cerveza')
    )
    op.create_index(op.f('ix_valoraciones_id'), 'valoraciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valoraciones_id'), table_name='valoraciones')
    op.drop_table('valoraciones')
    op.drop_index(op.f('ix_pasos_id'), table_name='pasos')
    op.drop_table('pasos')
    op.drop_index(op.f('ix_cerveza_ingredientes_id'), table_name='cerveza_ingredientes')
    op.drop_table('cerveza_ingredientes')
    op.drop_index(op.f('ix_cervezas_id'), table_name='cervezas')
    op.drop_table('cervezas')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_ingredientes_id'), table_name='ingredientes')
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
