"""add activa to cerveza

Revision ID: b57684242080
Revises: 87453607e16a
Create Date: 2026-06-27 13:11:36.583557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57684242080'
down_revision: Union[str, Sequence[str], None] = '87453607e16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cervezas', sa.Column('activa', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cervezas', 'activa')
    # ### end Alembic commands ###
